# Hexo 配置
## 文档: http://hexo.io/docs/configuration.html
## 源码: https://github.com/hexojs/hexo/

# 网站
title: Kano's Blog
subtitle:
description: Kano's Blog
author: Kano
language: zh-CN
timezone: Asia/Shanghai

url: https://kano.github.io

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 文章
new_post_name: :year:month:day-:title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# 分类 & 标签
default_category: 未分类
category_map:
tag_map:

# 日期 / 时间格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# 分页
per_page: 0
pagination_dir: page

# 扩展
theme: 3-hexo

#marked setting for markdown
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

location: Chang Sha
email: 632681127@qq.com

avatar: https://avatars.githubusercontent.com/u/48649646?v=4
social:
  github: https://github.com/Arohaaaa
  linkedin:

# flagcounter
flagcounter_href: # https://info.flagcounter.com/xxxx
flagcounter_img_src: # https://s01.flagcounter.com/xxxx
